# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Mod properties
mod_version = 2.0
maven_group = net.enderkitty
archives_name = reload_server_list
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.3

# Dependencies
architectury_api_version = 22.0.3
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.0+26.3
neoforge_version = 26.3.0.43-beta
