modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/LordEnder-Kitty/reload-server-list/issues"
license = "MIT"

[[mods]]
modId = "reload_server_list"
version = "${version}"
displayName = "Reload Server List"
authors = "LordEnder_Kitty"
description = '''
Ctrl+R reloads server selection screen
'''
iconFile = "assets/reload_server_list/icon.png"

[[dependencies.reload_server_list]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.reload_server_list]]
modId = "minecraft"
type = "required"
versionRange = "[26.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reload_server_list]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "reload_server_list.mixins.json"
